export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_ITEM_QUANTITY = "UPDATE_CART_ITEM_QUANTITY";

export const ADD_TO_BORROW = "ADD_TO_BORROW";
export const REMOVE_FROM_BORROW = "REMOVE_FROM_BORROW";
export const CLEAR_BORROW = "CLEAR_BORROW";
export const UPDATE_BORROW_ITEM_QUANTITY = "UPDATE_BORROW_ITEM_QUANTITY";